-- Criação da tabela Empresa
CREATE TABLE Empresa (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID único da empresa
    nome VARCHAR2(255) NOT NULL, -- Nome da empresa
    endereco VARCHAR2(255) NOT NULL -- Endereço da empresa
);

-- Criação da tabela Cliente
CREATE TABLE Cliente (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID único do cliente
    nome VARCHAR2(255) NOT NULL, -- Nome do cliente
    email VARCHAR2(255) NOT NULL UNIQUE, -- E-mail único do cliente
    empresa_id NUMBER, -- Referência para a empresa (chave estrangeira)
    FOREIGN KEY (empresa_id) REFERENCES Empresa(id) -- Chave estrangeira para Empresa
);

-- Criação da tabela Transacao
CREATE TABLE Transacao (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID único da transação
    valor NUMBER NOT NULL, -- Valor da transação
    data DATE NOT NULL, -- Data da transação
    cliente_id NUMBER, -- Referência para o cliente (chave estrangeira)
    FOREIGN KEY (cliente_id) REFERENCES Cliente(id) -- Chave estrangeira para Cliente
);

-- Criação da tabela ChurnPrediction
CREATE TABLE ChurnPrediction (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- ID único da predição de churn
    probabilidadeChurn NUMBER NOT NULL, -- Probabilidade de churn
    dataPredicao DATE NOT NULL, -- Data da predição
    cliente_id NUMBER, -- Referência para o cliente (chave estrangeira)
    FOREIGN KEY (cliente_id) REFERENCES Cliente(id) -- Chave estrangeira para Cliente
);
